config/routes.rb
FlashCardMNGer::Application.routes.draw do
 
  root 'static_pages#index'
  
  shallow do
    resources :decks do
      resources :cards 
    end
  end
  
  resources :user_sessions
  resources :users do 
    member do
      put 'set_current_deck'
    end
  end

  put 'check_translation', to: 'review#check_translation'
  get 'login',             to: 'user_sessions#new'     
  post 'logout',           to: 'user_sessions#destroy' 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login, only: [:index]
  before_action :current_user?

  def index
    if params[:card_id]
      @card = current_user.cards.find(params[:card_id])
    elsif current_user.cards.first
      @card = current_user.pending_cards.first
    elsif current_user.decks.empty?
      redirect_to :new_deck, notice: 'Необходимо создать колоду и добавить туда карточки.'
    else
      redirect_to :decks, notice: 'Необходимо добавить карточки в колоду.'
    end

    Rails.logger.warn "PASSED ALL CHECKS";
    respond_to do |format|
      format.js {
        Rails.logger.warn params.inspect
        render_to_string(partials: "card_review", formats: :html, layout: false)
               }
      format.html { Rails.logger.warn "RENDERING HTML"; }
    end

  end

  def current_user?
    if !current_user
      flash[:notice] = "Войдите или зарегистрируйтесь"
      redirect_to new_user_path
    end
  end

end

app/views/static_pages/_card_review.html.erb
<% if @card %>
  <h1 class="deck-title">
    <%= current_user.current_deck.title if current_user.current_deck_id %>
  </h1>
  <div><%= image_tag @card.image_url if @card.image? %></div>
  <span class="original-text">
    <%= @card.original_text %>
  </span>
  <%= form_tag check_translation_path, method: :put do %>
    <%= label_tag        :translation, "Введите перевод:" %>
    <%= text_field_tag   :translation %>
    <%= hidden_field_tag :card_id, @card.id %>
    <%= hidden_field_tag :time, '' %>
    <%= submit_tag "Проверка" %>
  <% end %> 
<% elsif current_user %>
  <div class="alert alert-warning">
    На сегодня все карточки закончились. Приходите завтра.
  </div>
<% end %>

app/views/static_pages/index.html.erb
<p class="big-font">
  Первый в мире удобный менеджер флеш-карточек. Именно так.
</p>
<% if @card %>
  <h1 class="deck-title">
    <%= current_user.current_deck.title if current_user.current_deck_id %>
  </h1>
  <div><%= image_tag @card.image_url if @card.image? %></div>
  <span class="original-text">
    <%= @card.original_text %>
  </span>
  <%= form_tag check_translation_path, method: :put do %>
    <%= label_tag        :translation, "Введите перевод:" %>
    <%= text_field_tag   :translation %>
    <%= hidden_field_tag :card_id, @card.id %>
    <%= hidden_field_tag :time, '' %>
    <%= submit_tag "Проверка" %>
  <% end %>
<% elsif current_user %>
  <div class="alert alert-warning">
    На сегодня все карточки закончились. Приходите завтра.
  </div>
<% end %>