config/routes.rb
FlashCardMNGer::Application.routes.draw do
 
  root 'static_pages#index'
  
  shallow do
    resources :decks do
      resources :cards 
    end
  end
  
  resources :user_sessions
  resources :users do 
    member do
      put 'set_current_deck'
    end
  end

  put 'check_translation', to: 'review#check_translation'
  get 'login',             to: 'user_sessions#new'     
  post 'logout',           to: 'user_sessions#destroy' 
end

app/models/card.rb
class Card < ActiveRecord::Base

  belongs_to :user
  belongs_to :deck

  validates :original_text, :translated_text, :user_id, :deck_id, presence: true 
  
  scope :pending, -> { where("review_date <= ?", Time.now).order("RANDOM()") } 
  
  mount_uploader :image, ImageUploader

  before_create :set_default_review_date

  def check(translation, typo_count, time)
    case Levenshtein.distance(translated_text, translation) 
    when 0
      process_correct_answer(typo_count, time)
      :success
    when 1..3
      :typo
    else
      process_incorrect_answer
      :error
    end
  end

  def process_correct_answer(typo_count, time)
    increment(:numb_correct_answers)
    renew_attributes(typo_count, time)
  end

  def process_incorrect_answer
    if numb_incorrect_answers < 3
      increment(:numb_incorrect_answers)
      save
    else
      reset_attributes
    end
  end

  def renew_attributes(typo_count, time)
    supermemo = SuperMemo.new(interval, ef, typo_count, time, translated_text.length, numb_correct_answers)
    new_ef = supermemo.e_factor
    new_interval = supermemo.interval
    new_review_date = Time.now + new_interval.day
    update_attributes(ef: new_ef, interval: new_interval, review_date: new_review_date, numb_incorrect_answers: 0) 
  end  
  
  def reset_attributes
    update_attributes(numb_correct_answers: 0, numb_incorrect_answers: 0, ef: 1.3, interval: 1, review_date: Time.now)
  end

  def set_default_review_date
    self.review_date = Time.now
  end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  before_action :find_card, only: [:show, :edit, :update, :destroy]
  before_action :find_deck, only: [:index, :new, :create]

  def index
    @cards = @deck.cards
  end

  def new
    @card = @deck.cards.new
  end
   
  def create
    @card = @deck.cards.create(card_params.merge(user_id: current_user.id))
   
    if @card.save
      redirect_to @card
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update

    if @card.update(card_params)
      redirect_to @card
    else
      render 'edit'
    end

  end

  def destroy
    @card.destroy
    
    redirect_to deck_cards_path(@card.deck_id)    
  end
   
  private
  
  def card_params
    params.require(:card).permit(:original_text, :translated_text, :review_date, :image)
  end

  def find_card
    @card = current_user.cards.find(params[:id])
  end

  def find_deck
    @deck = current_user.decks.find(params[:deck_id])
  end

end

app/views/cards/_cards.html.erb
<table align="center">
  <tr>
    <th>Слово</th>
    <th>Перевод</th>
    <th>Дата пересмотра</th>
    <th>Изображение</th>
    <th></th>
  </tr>
  <% @deck.cards.each do |card| %>
  <div>Привет</div>
    <tr>
      <td><%= card.original_text %></td>
      <td><%= card.translated_text %></td>
      <td><%= card.review_date.try(:strftime, "%d/%m/%Y") %></td>
      <td><%= image_tag card.image_url(:thumb) if card.image? %></td>
      <td>
        <%= link_to "Показать", card_path(card) %><br><%= link_to "Редактировать", edit_card_path(card) %> /
        <%= link_to "Удалить", card_path(card), method: :delete, data: { confirm: 'Вы уверены, что хотите удалить безвозвратно эту флэш-карточку?' }  %>
      </td>
    </tr>
  <% end %>
</table>

app/views/cards/_form.html.erb
<%= simple_form_for [@deck, @card] do |f| %>
  <%= f.input  :original_text,   label: "Слово:" %>
  <%= f.input  :translated_text, label: "Перевод:" %>
  <%= f.input  :image,           label: "Изображение:" %>
  <%= f.button :submit, "OK",    class: "btn btn-large btn-primary" %>
<% end %>

app/views/cards/edit.html.erb
<h1>Редактирование карточки</h1>

<%= render 'form' %>
<%= link_to 'Назад', deck_cards_path(@card.deck_id) %>

app/views/cards/index.html.erb
<h1>Все карточки</h1>
<h1>колода <span class="deck-title"><%= @deck.title %></span></h1>

<%= render "cards" %> 

<div><%= link_to "Добавить карточку", new_deck_card_path(params[:deck_id]) %></div>
<div><%= link_to "Назад к колодам", decks_path %></div>

app/views/cards/new.html.erb
<h1>Новая карточка</h1>

<%= render 'form' %>
<%= link_to 'Назад', deck_cards_path(@deck) %>

app/views/cards/show.html.erb
<p>
  <strong>Слово:</strong>
  <%= @card.original_text %>
</p>
 
<p>
  <strong>Перевод:</strong>
  <%= @card.translated_text %>
</p>

<p>
  <strong>Время пересмотра:</strong>
  <%= @card.review_date %>
</p>

<p>
  <%= image_tag @card.image_url if @card.image? %> 
</p>

<%= link_to "Редактировать", edit_card_path(@card) %>/ 
<%= link_to "Удалить", card_path(@card), method: :delete, data: { confirm: 'Вы уверены, что хотите удалить безвозвратно эту флэш-карточку?' } %><br>
<%= link_to 'Назад', deck_cards_path(@card.deck_id) %>