config/routes.rb
FlashCardMNGer::Application.routes.draw do
 
  root 'static_pages#index'
  
  shallow do
    resources :decks do
      resources :cards 
    end
  end
  
  resources :user_sessions
  resources :users do 
    member do
      put 'set_current_deck'
    end
  end

  put 'check_translation', to: 'review#check_translation'
  get 'login',             to: 'user_sessions#new'     
  post 'logout',           to: 'user_sessions#destroy' 
end

app/models/deck.rb
class Deck < ActiveRecord::Base

  belongs_to :user
  
  has_many :cards, dependent: :destroy

  validates :title, :user_id, presence: true 

  after_destroy do |deck|
    user = User.where("current_deck_id = ?", deck.id).first
    user.update_attribute(:current_deck_id, nil) if user
  end

end

app/controllers/decks_controller.rb
class DecksController < ApplicationController

  before_action :find_deck, only: [:show, :edit, :update, :destroy]

  def index
    @decks = current_user.decks
  end

  def new
    @deck = current_user.decks.new
  end

  def show
    redirect_to deck_cards_path(@deck)
  end

  def create
    @deck = current_user.decks.create(deck_params)

    if @deck.save
      redirect_to decks_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @deck.update(deck_params)
      redirect_to @deck
    else
      render 'edit'
    end
  end

  def destroy
    @deck.destroy

    redirect_to decks_path
  end

  private
  
  def deck_params
    params.require(:deck).permit(:title)
  end

  def find_deck
    @deck = current_user.decks.find(params[:id])
  end

end

app/views/decks/_form.html.erb
<%= simple_form_for @deck do |f| %>
  <%= f.input  :title, label: "Колода:" %>
  <%= f.button :submit, "OK", class: "btn btn-large btn-primary" %>
<% end %>

app/views/decks/edit.html.erb
<h1>Редактирование колоды</h1>

<%= render 'form' %>
<%= link_to 'Назад', decks_path %>

app/views/decks/index.html.erb
<h1>Все колоды</h1>
 
<table align="center">
  <tr>
    <th>Колода</th>
    <th></th>
    <th></th>
  </tr>
  <% @decks.each do |deck| %>
    <tr>
      <td><%= deck.title %></td>
      <td>
        <div>
          <%= link_to "Добавить карточку", new_deck_card_path(deck)%>
        </div>
        <div>
          <%= link_to "Показать", deck_path(deck) %> /
          <%= link_to "Редактировать", edit_deck_path(deck) %> / 
          <%= link_to "Удалить", deck_path(deck), method: :delete, data: { confirm: 'Вы уверены, что хотите удалить безвозвратно эту колоду? Если вы нажмете ОК, то все флэш-карточки, содержащиеся в этой колоде, будут удалены' }  %>
        </div>
      </td>
      <td><%= link_to "Сделать текущей", set_current_deck_user_path(deck), method: :put %></td>
    </tr>
  <% end %>
</table>

app/views/decks/new.html.erb
<h1>Новая колода</h1>

<%= render 'form' %>
<%= link_to 'Назад', decks_path %>