config/routes.rb
FlashCardMNGer::Application.routes.draw do
 
  root 'static_pages#index'
  
  shallow do
    resources :decks do
      resources :cards 
    end
  end
  
  resources :user_sessions
  resources :users do 
    member do
      put 'set_current_deck'
    end
  end

  put 'check_translation', to: 'review#check_translation'
  get 'login',             to: 'user_sessions#new'     
  post 'logout',           to: 'user_sessions#destroy' 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Флэшкарточкер</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
  <section class="container">

    <header class="row page-header clearfix">
      <h1><%= link_to 'Флэшкарточкер', root_path, class: "logo" %></h1>
      <% if current_user %>
        <ul class="nav nav-pills navbar-right navi">
          <li><%= link_to 'Колоды', decks_path %>
            <ul class="nav nav-pills navbar-right navi sub-menu">
              <li><%= link_to 'Добавить колоду', new_deck_path %></li>
            </ul>
          </li>
        </ul>
      <% else %>
        <ul class="nav nav-pills navbar-right navi">
          <li><%= link_to "Регистрация", new_user_path %></li>
          <li><%= link_to "Войти", :login %></li>
        </ul>
      <% end %>
    </header>

    <nav>
      <% if current_user %>
      <div>
        <%= current_user.email %> |
        <%= link_to "Редактировать", edit_user_path(current_user) %> |
        <%= link_to "Выйти", :logout, method: :post %>
      </div>
      <% end %>
    </nav>
    
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %> msg"><%= value %></div>
    <% end %>

    <section class="content">
     
      
      <%= yield %>
    </section>
    
  </section>
</body>

</html>